version: "2.3"
services:
  web:
    build: .
    container_name: "sarah-otp-web"
    env_file: ./.env
    ports:
      - "${HTTPS_PORT}:8000"
      - "${HTTP_PORT}:8001"
    environment:
      - HTTPS_PORT=8000
      - HTTP_PORT=8001
      - TLS_CERT_FILE=/app/cert.pem
      - TLS_KEY_FILE=/app/key.pem
    volumes:
      - ${TLS_CERT_FILE}:/app/cert.pem
      - ${TLS_KEY_FILE}:/app/key.pem